### ISSUE TITLE
Fix broken unit-tests

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#116]
Noticed broken tests while working on writing new ones to solve https://github.com/FixMyBerlin/fixmy.platform/issues/104

```
> jest --verbose --config=jest/jest.config.js

  console.warn config.js:285
    No CONFIG_ENV defined. Using production API by default.

  console.warn config.js:285
    No CONFIG_ENV defined. Using production API by default.

  console.warn config.js:285
    No CONFIG_ENV defined. Using production API by default.

 PASS  src/pages/KatasterKI/tests/utils.unit.test.ts
  Kataster utils
    √ Successfully validates an error free instance of the ProfileRequest Json Schema (10ms)

  console.warn config.js:285
    No CONFIG_ENV defined. Using production API by default.

 PASS  src/pages/Reports/state/tests/ErrorState.unit.test.js
  ErrorState reducer and actions
    √ returns the initial state for an empty action (8ms)
    √ adds an error with a default message with no further details about the error (1ms)
    √ adds an error with a custom message (1ms)
    √ adds an error with a custom ProceedButton spec
    √ removes an error (1ms)

  console.error node_modules/redux/lib/redux.js:324
    No reducer provided for key "SubmitReportState"

 FAIL  src/pages/Reports/state/tests/OverviewMapState.unit.test.js
  OverviewMapState reducer and actions
    √ returns the initial state for an empty action (4ms)
    √ sets the popup display position of a selected report (1ms)
    √ resets the map state
    async actions
      × fetches reports and creates REPORTS_FETCH_COMPLETE (165ms)
      √ fails to fetch reports and creates ADD_ERROR (3ms)
      √ sets the selectedReport if reports have been fetched already (1ms)
      × sets the selectedReport and - if no reports have been fetched yet - fetches the repo
rts before (1ms)

  ● OverviewMapState reducer and actions › async actions › fetches reports and creates REPOR
TS_FETCH_COMPLETE

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
        Object {
          "type": "Reports/OverviewMapState/REPORTS_FETCH_PENDING",
        },
        Object {
    -     "payload": Array [
    -       Object {
    -         "address": "Alexandrinenstraße 118, 10969 Berlin",
    -         "description": "",
    -         "details": Object {
    -           "fee": 2,
    -           "number": 18,
    -           "placement": "SIDEWALK",
    -           "subject": "BIKE_STANDS",
    -         },
    -         "geometry": Object {
    -           "coordinates": Array [
    -             13.40061834673159,
    -             52.50075090458924,
    -           ],
    -           "type": "Point",
    -         },
    -         "id": 2,
    -         "liked_by_user": false,
    -         "likes": 0,
    -         "photo": Object {
    -           "copyright": null,
    -           "src": "https://fmb-aws-bucket.s3.amazonaws.com/photos/4598b3b2-3c4.jpg",
    -         },
    -         "status": "new",
    -         "status_reason": null,
    -       },
    -       Object {
    -         "address": "Mariane-Von-Rantzau-Straße 2, 10243 Berlin",
    -         "description": null,
    -         "details": Object {
    -           "fee": 0,
    -           "number": 3,
    -           "placement": "STREET",
    -           "subject": "BIKE_STANDS",
    -         },
    -         "geometry": Object {
    -           "coordinates": Array [
    -             13.43891385584493,
    -             52.50686916908651,
    -           ],
    -           "type": "Point",
    -         },
    -         "id": 1,
    -         "liked_by_user": false,
    -         "likes": 0,
    -         "photo": null,
    -         "status": "new",
    -         "status_reason": null,
    -       },
    -       Object {
    -         "address": "Am Postbahnhof 23, 10243 Berlin",
    -         "description": "test",
    -         "details": Object {
    -           "fee": 0,
    -           "number": 3,
    -           "placement": "STREET",
    -           "subject": "BIKE_STANDS",
    -         },
    -         "geometry": Object {
    -           "coordinates": Array [
    -             13.43754677753566,
    -             52.5073314413834,
    -           ],
    -           "type": "Point",
    -         },
    -         "id": 3,
    -         "liked_by_user": false,
    -         "likes": 0,
    -         "photo": Object {
    -           "copyright": null,
    -           "src": null,
    -         },
    -         "status": "new",
    -         "status_reason": null,
    -       },
    -       Object {
    -         "address": "Modersohnstraße 12, 10245 Berlin",
    -         "description": "",
    -         "details": Object {
    -           "fee": 0,
    -           "number": 7,
    -           "placement": "SIDEWALK",
    -           "subject": "BIKE_STANDS",
    -         },
    -         "geometry": Object {
    -           "coordinates": Array [
    -             13.45896882090108,
    -             52.50699566558592,
    -           ],
    -           "type": "Point",
    -         },
    -         "id": 4,
    -         "liked_by_user": false,
    -         "likes": 1,
    -         "photo": Object {
    -           "copyright": null,
    -           "src": "https://fmb-aws-bucket.s3.amazonaws.com/photos/cafb5486-167.jpg",
    -         },
    -         "status": "new",
    -         "status_reason": null,
    -       },
    -       Object {
    -         "address": "Painstation, Berlin, 10243",
    -         "description": "",
    -         "details": Object {
    -           "fee": 1,
    -           "number": 3,
    -           "placement": "STREET",
    -           "subject": "BIKE_STANDS",
    -         },
    -         "geometry": Object {
    -           "coordinates": Array [
    -             13.44196228281942,
    -             52.51729963135287,
    -           ],
    -           "type": "Point",
    -         },
    -         "id": 5,
    -         "liked_by_user": false,
    -         "likes": 1,
    -         "photo": Object {
    -           "copyright": null,
    -           "src": "https://fmb-aws-bucket.s3.amazonaws.com/photos/2fe3237d-d1c.jpg",
    +     "error": true,
    +     "payload": Object {
    +       "message": "Fehler beim Laden der Meldungen",
    +       "proceedFunc": null,
    +       "proceedMessage": null,
          },
    -         "status": "new",
    -         "status_reason": null,
    -       },
    -     ],
    -     "type": "Reports/OverviewMapState/REPORTS_FETCH_COMPLETE",
    +     "type": "Reports/ReportsDialogState/ErrorState/ADD_ERROR",
        },
      ]

      74 |         // test action sequence
      75 |         expect(store.getActions())
    > 76 |           .toEqual(expectedActions);
         |            ^
      77 | 
      78 |         // test reducer
      79 |         expect(reducer(initialState, {

      at toEqual (src/pages/Reports/state/tests/OverviewMapState.unit.test.js:76:12)

  ● OverviewMapState reducer and actions › async actions › sets the selectedReport and - if
no reports have been fetched yet - fetches the reports before

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
        "Reports/OverviewMapState/REPORTS_FETCH_PENDING",
    -   "Reports/OverviewMapState/REPORTS_FETCH_COMPLETE",
    +   "Reports/ReportsDialogState/ErrorState/ADD_ERROR",
        "Reports/OverviewMapState/SET_SELECTED_REPORT",
      ]

      158 |           // only test action sequence
      159 |           expect(store.getActions().map(action => action.type))
    > 160 |             .toEqual(expectedActionTypes);
          |              ^
      161 |         });
      162 |     });
      163 |   });

      at toEqual (src/pages/Reports/state/tests/OverviewMapState.unit.test.js:160:14)

  console.error src/pages/Reports/state/OverviewMapState.js:53
    Fehler beim Laden der Meldungen: TypeError: Cannot read property 'json' of undefined

 FAIL  src/pages/Reports/state/tests/SubmitReportState.unit.test.js
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` opti
on):
    src/pages/KatasterKI/state.ts:214:33 - error TS7006: Parameter 'props' implicitly has an
 'any' type.

    214 export function setRequestState(props): Action {
                                        ~~~~~

Test Suites: 2 failed, 2 passed, 4 total
Tests:       2 failed, 11 passed, 13 total
Snapshots:   0 total
Time:        6.524s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1


```

**Comment by geomC** [comment]
The test seem to fail because of `ky` and its usage in a node environment during testing: https://github.com/sindresorhus/ky/issues/202

**Comment by geomC** [comment]
I Cannot yet put the finger on it, but: If I use plain `fetch`, the requests work:

![image](https://user-images.githubusercontent.com/12786207/68621700-b2eff380-04d0-11ea-8627-3a658796c455.png)

**Comment by sholladay** [comment]
Could you show me a stack trace that makes you believe this is related to sindresorhus/ky#202?

**Comment by ciex** [comment]
@geomC I don't see this test failing anymore. I will close this ticket, please reopen if there is an unresolved issue I'm not seeing!
