### ISSUE TITLE
[Frontend] Unit tests for sorting lists fail

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#427]
#### Issue description

Running `npm run test` leads to the following unexpected error output
```

 FAIL  src/utils/tests/utils.unit.test.ts
  sortByKey
    √ sorts lists of objects with a default sort (8ms)
    √ sorts lists of objects by id
    × sorts lists of objects by likes (12ms)
    × sorts lists of objects by construction date (14ms)

  ● sortByKey › sorts lists of objects by likes

    expect(received).toEqual(expected) // deep equality

    Expected: "[88,97,94,93,69,90,89,95,87,86,85,49,53,62,48,72,73,96,83,67,76,77
,66,71,70,91,63,80,59,47,68,54,61,60,58,4,79,56,57,20,82,65,23,50,84,18,78,81,27,
37,51,75,92,26,52,40,42,74,35,36,10,34,55,11,6,7]"
    Received: "[49,53,62,69,85,86,87,88,89,90,93,94,95,97,48,67,72,73,76,77,83,96
,63,66,70,71,80,91,47,54,58,59,60,61,68,4,20,56,57,79,82,23,50,65,84,18,27,78,81,
37,51,75,26,92,40,52,42,74,10,35,36,34,6,11,55,7]"

      21 |   it('sorts lists of objects by likes', () => {
      22 |     const sortOutput = projectList.sort(sortByKey('likes'));
    > 23 |     expect(JSON.stringify(sortOutput.map((obj) => obj.id))).toEqual(
         |                                                             ^
      24 |       JSON.stringify(projectListSorted.byLikes)
      25 |     );
      26 |   });

      at Object.<anonymous> (src/utils/tests/utils.unit.test.ts:23:61)

  ● sortByKey › sorts lists of objects by construction date

    expect(received).toEqual(expected) // deep equality

    Expected: "[88,89,87,85,62,61,59,55,94,86,93,92,50,11,57,56,90,54,68,60,53,66
,10,42,63,27,95,7,81,76,80,67,37,83,51,73,75,58,49,79,26,48,52,82,40,23,91,84,74,
78,35,96,36,4,70,20,77,6,69,71,34,18,65,72,97,47]"
    Received: "[85,87,88,89,62,59,61,86,90,93,94,54,60,68,56,57,50,92,11,55,53,63
,66,27,42,10,95,49,69,97,48,67,72,73,76,77,83,96,70,71,80,91,47,58,4,20,79,82,23,
65,84,18,78,81,37,51,75,26,40,52,74,35,36,34,6,7]"

      30 |       sortByKey('construction_completed_date')
      31 |     );
    > 32 |     expect(JSON.stringify(sortOutput.map((obj) => obj.id))).toEqual(
         |                                                             ^
      33 |       JSON.stringify(projectListSorted.byDate)
      34 |     );
      35 |   });

      at Object.<anonymous> (src/utils/tests/utils.unit.test.ts:32:61)

```

I wonder why the CI did not catch that. Might this be related to https://github.com/FixMyBerlin/fixmy.platform/issues/426?

**Comment by cafca** [comment]
This test succeeds on my machine and in CI

```
Thu, 03 Sep 2020 15:13:49 GMT PASS src/utils/tests/utils.unit.test.ts
Thu, 03 Sep 2020 15:13:49 GMT   sortByKey
Thu, 03 Sep 2020 15:13:49 GMT     ✓ sorts lists of objects with a default sort (2ms)
Thu, 03 Sep 2020 15:13:49 GMT     ✓ sorts lists of objects by id (1ms)
Thu, 03 Sep 2020 15:13:49 GMT     ✓ sorts lists of objects by likes
Thu, 03 Sep 2020 15:13:49 GMT     ✓ sorts lists of objects by construction date (1ms)
```

Can you confirm that the sorting of the project list on [this page](https://fixmyberlin.de/analyse/planungen) is not working for you?

**Comment by s-pic** [comment]
> Can you confirm that the sorting of the project list on this page is not working for you?

I can confirm that the functionality works as expected in the deployment, plannings do get sorted by likes.  

> This test succeeds on my machine and in CI

This is all really strange. I am not going to ask you what .env props you are using since thoses tests as well as the covered logic 
is very isolated (there is no api call hapening or so).

Also the expected values do not make much sense to me: I would expect natural numbers in ascending order, instead I am seing a row with numbers that are not sorted at all. 

I know that ´JSON.stringify()´  is not reliably sorting properties in objects (see e.g. https://github.com/auth0/node-jsonwebtoken/issues/404), but I have not read about any problems regarding Arrays.

I am a bit clueless here.
